### ISSUE TITLE
hellotext_session parameter

### ISSUE THREAD

**Issue by pelcasandra** [hellotext/hellotext.js#2]
The library is still expecting the session parameter as `hellotext_session_id` instead of the newer `hellotext_session` name.

**Comment by rockwellll** [comment]
Done

**Comment by pelcasandra** [comment]
Also here

https://github.com/hellotext/hellotext.js/blob/4a0513c34ed9bd46e0d335e2c1dae9aacfcee605/lib/hellotext.js#L78

**Comment by rockwellll** [comment]
Done
